trigger:
  - master
  - dev
  
stages:
  - stage: build
    displayName: Routine Build

    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: 'ubuntu-18.04'

        steps:
        - script: yarn
          displayName: Restore Packages

        - script: yarn build
          displayName: Webpack Build

        - publish: dist
          artifact: timeline

  - stage: deploy
    displayName: Deploy
    dependsOn: build
    condition: eq(variables['Build.SourceBranchName'], 'master')

    jobs:
    - deployment: deploy
      displayName: Deploy to Server
      environment: 
        name: timeline-server
        resourceType: VirtualMachine
        tags: linux
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: timeline

            - script: |
                rm -rf /var/www/timeline/*
                cp -r $PIPELINE_WORKSPACE/timeline/. /var/www/timeline/
              displayName: 'Copy Files'
              failOnStderr: true
