trigger:
- master

stages:
- stage: build
  displayName: Routine Build

  jobs:
    - job: build
      displayName: Build
      pool:
        vmImage: 'ubuntu-18.04'

      steps:
      - script: yarn --verbose
        displayName: Restore Packages

      - script: yarn build
        displayName: Webpack Build

      - publish: dist
        artifact: timeline

- stage: deploy
  displayName: Deploy
  dependsOn: build
  condition: eq(variables['Build.SourceBranchName'], 'master')

  jobs:
  - deployment: deploy
    displayName: Deploy to Server
    environment: 
      name: timeline-server
      resourceType: VirtualMachine
      tags: linux
    strategy:
      runOnce:
        preDeploy:
          steps:
          - download: none

          - download: current
            artifact: timeline
        deploy:
          steps:
          - script: |
              rm -rf /var/www/timeline/*
              cp -r $PIPELINE_WORKSPACE/timeline/. /var/www/timeline/
            displayName: 'Copy Files'
            failOnStderr: true
